airsonic-advanced/airsonic-advanced

.travis.yml
install/docker/dockerhub_push.sh

This PR automates dev builds to be pushed out to GitHub Releases ~and Docker Hub~ under the Edge Release Channel per discussion in ~https://github.com/airsonic/airsonic/issues/1373~
I also think we should automate the Stable Releases, but that's a later priority. I'm eager to get the dev builds going so the massive backlog of PRs is reduced.
This PR:
- Divides builds into 2 stages: `test` and `deploy_edge`
- `deploy_edge` only runs
- on `master`
- for merges/pushes (i.e. no PRs)
- If all jobs in the `test` stage pass
- Edge deploys
- Build airsonic war
- Build the docker container
- Tag the commit it's building on (necessary for GitHub Release)
- push to GitHub Releases with a Preleaase Build
- ~push to Docker Hub~
- Tags are of the type `MAVEN_BUILD+DATETIMEOFBUILD+COMMITHASH` in keeping …

Modify travis to start running builds

---

airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/spring/DatabaseConfiguration.java

This builds on #18 and #21 and switches the DB connection pool to the default provided by Spring boot, removing explicit dependency to Apache's DBCP2 in the process.
The default is either Hikari, Tomcat, or DBCP2, whichever is found on the system first, in that order.
This is Step 3 of a series of PRs each of which will build on each other
Next up: Testing rules
This is the same PR as https://github.com/airsonic/airsonic/pull/1368

Spring Boot 2 Upgrade: Part 3 - Remove DBCP2, switch to Tomcat/Hikari

---

airsonic-main/src/test/java/org/airsonic/player/dao/DaoTestCaseBean2.java
airsonic-main/src/test/java/org/airsonic/player/service/LegacyDatabaseStartupTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaScannerServiceTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/metadata/MetaDataFactoryTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/AbstractAirsonicHomeTest.java
airsonic-main/src/test/java/org/airsonic/player/service/search/QueryFactoryTestCase.java

This builds on #18, #21 and #22 and cleans up some tests to use the proper annotations and rules. This is necessary prior to upgrade because Spring Boot 2 does not allow the old test rules and the new to coexist.
This is Step 4 of a series of PRs each of which will build on each other
Next up: Move MVC Config out of Application and into Servlet
This is the same PR as https://github.com/airsonic/airsonic/pull/1369

Spring Boot 2 Upgrade: Part 4 - Move Tests to Rules

---

airsonic-main/src/main/java/org/airsonic/player/Application.java
airsonic-main/src/main/java/org/airsonic/player/spring/ServletConfiguration.java

This builds on #18, #21, #22 and #23 and moves MVC Config to Servlet.java instead of littering the root Application.java. This is a purely cosmetic change so that churn in Application.java is reduced. It confers benefits in the future for slicing tests, which don't need to have heavy bindings in the root context.
This is Step 5 of a series of PRs each of which will build on each other
Next up: Spring Boot 2 and dependency upgrades
This is the same PR as https://github.com/airsonic/airsonic/pull/1370

Spring Boot 2 Upgrade: Part 5 - Move MVC Config to Servlet

---

.travis.yml
airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/domain/Version.java
airsonic-main/src/main/java/org/airsonic/player/service/VersionService.java
airsonic-main/src/main/java/org/airsonic/player/util/Util.java

- Generate build info and store it in a file at build time
- Get release tag for docker and github releases from build info generated
- Retrieve build info during runtime
- Retrieve version updates from the correct repo (airsonic-advanced)

Fix retrieval of versions from airsonic-advanced repo instead of airsonic and get release tags from build info

---

airsonic-main/src/main/webapp/WEB-INF/jsp/homePager.jsp

Same PR as https://github.com/airsonic/airsonic/pull/1413
This adds a refresh link to all homePager.jsp browse methods in a
consistent place, so that users can easily refresh the proper frame
without causing a whole page refresh that would interrupt the web
player.
This is a follow-on to #1339 which removed the auto-refresh feature.
A side effect of this cleanup was to change all spacing between sets
of elements to a standard 2em to the right which made the layout
less convoluted.

Added refresh link to all home navigation types

---

airsonic-main/src/main/java/org/airsonic/player/Application.java
airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/test/java/org/airsonic/player/service/SettingsServiceTestCase.java

Instead of removing obsolete property keys from the .properties file, migrate them to the new keys
Removal (what is currently done) is also possible if a particular key isn't used anymore at all.
This is done in preparation for major version upgrades, where key names are often renamed. In airsonic, this had to be done manually prior to upgrade. This PR allows airsonic to handle it automatically. In particular, database property names might change between airsonic-advanced and airsonic, and between airsonic 10 and 11. This PR should handle all the changes seamlessly.
Updates to the properties file (if needed) happens at Application startup. Obsolete keys do not need to be removed at every save point.
Property migration is handled as a chain, and as such order of migration is important …

Migrate properties automatically

---

airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java

- Installation step determination does not factor .exe for Windows paths (ffmpeg.exe is not recognized)
- Copying temp files when files have nonascii filenames fails

TranscodingService bugfixes

---

airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java

Currently we completely overwrite and revamp user tables when updating byte counts.
This leads to race conditions such as:
- User changes song
- TransferStatus want to update user's byte counts for the previous song
- As part of the `updateUser()` call, user roles are deleted
- In a different thread, new song request checks auth access and sees no roles for the user, thus is denied.
- User roles are added again by thread 1.
Additionally this may lead to issues like:
- Shutdown in the middle of a byte update call will lead to user roles getting deleted

Update byte counts safely and not unnecessarily rewrite the roles

---

airsonic-main/src/main/java/org/airsonic/player/ajax/TransferService.java
airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
airsonic-main/src/main/java/org/airsonic/player/controller/StatusController.java
airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
airsonic-main/src/main/java/org/airsonic/player/controller/UploadController.java
airsonic-main/src/main/java/org/airsonic/player/domain/TransferStatus.java
airsonic-main/src/main/java/org/airsonic/player/io/PlayQueueInputStream.java
airsonic-main/src/main/java/org/airsonic/player/service/JukeboxJavaService.java
airsonic-main/src/main/java/org/airsonic/player/service/JukeboxLegacySubsonicService.java
airsonic-main/src/main/java/org/airsonic/player/service/StatusService.java

Should help with performance slightly so everyone isn't locking on the object instances and waiting

Remove sync locks everywhere in StatusService and TransferStatus

---

airsonic-main/src/main/java/org/airsonic/player/ajax/TransferService.java
airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
airsonic-main/src/main/java/org/airsonic/player/controller/JAXBWriter.java
airsonic-main/src/main/java/org/airsonic/player/controller/StatusController.java
airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/controller/UploadController.java
airsonic-main/src/main/java/org/airsonic/player/domain/TransferStatus.java
airsonic-main/src/main/java/org/airsonic/player/io/PlayQueueInputStream.java
airsonic-main/src/main/java/org/airsonic/player/service/JukeboxJavaService.java
airsonic-main/src/main/java/org/airsonic/player/service/JukeboxLegacySubsonicService.java
airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/main/java/org/airsonic/player/service/StatusService.java
airsonic-main/src/main/java/org/airsonic/player/spring/ResourceRegionReusableHttpMessageConverter.java
airsonic-main/src/main/java/org/airsonic/player/util/FileUtil.java
airsonic-main/src/main/java/org/airsonic/player/util/PipeStreams.java
airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java
airsonic-main/src/test/java/org/airsonic/player/util/PipeStreamsTest.java

This PR updates DownloadController to rely on Spring's Resources class instead of manual byte transferring.
The previous implementation had the following issues:
- ETags used only for MediaFiles, and prone to issues
- The ETag in use (when used) was the MediaFile id which does not guarantee that the underlying resource has changed, making caching incorrect or useless
- Last-Modified only used for MediaFiles
- Range requests are incorrectly implemented and do not comply with IETF RFC7233 (https://tools.ietf.org/html/rfc7233)
- Range requests only implemented for MediaFiles
- Only some types of range requests supported (no suffix byte ranges, or multiple ranges)
- Content-Range header incorrectly set for 206 Partial Content responses, even for MediaFiles
- This effectively makes Range …

DownloadController to handle headers and streams correctly

---

airsonic-main/src/main/java/org/airsonic/player/spring/WebsocketConfiguration.java

so default cdn version isn't used (causing version conflicts)

Provide sockjs client lib location

---

airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java

Problem appears when we retrieve creds with no Apps as args.
This may happen if neither Last.fm nor Listenbrainz are enabled in AudioScrobblerService (so we shouldn't even check the db for creds at all).
Manifests as
```
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select username, app_username, credential, encoder, app, created, updated, expiration, comment from user_credentials where username=? and app in ()]; nested exception is java.sql.SQLException: Unexpected token: ) in statement [select username, app_username, credential, encoder, app, created, updated, expiration, comment from user_credentials where username=? and app in ()]
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator. …
```

Do a sanity arg length check before sending sql to db to retrieve credentials

---

airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java

Bug found when trying to add external db testing.
Manifests as:
```
[ERROR] testGetUserByName  Time elapsed: 0.665 s  <<< ERROR!
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [insert into user_credentials (username, app_username, credential, encoder, app, created, updated, expiration, comment) values (?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of org.airsonic.player.domain.UserCredential$App. Use setObject() with an explicit Types value to specify the type to use.
at org.airsonic.player.dao.UserDaoTestCase.testGetUserByName(UserDaoTestCase.java:150)
Caused by: org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of …
```

Fix for postgres not taking enums

---

airsonic-main/src/main/resources/liquibase/db-changelog.xml

Liquibase changed how the blob type was handled in 3.5.2 for Postgres. Prior it was a bytea, after it was an oid.
https://liquibase.jira.com/browse/CORE-1863
We changed liquibase version in https://github.com/airsonic/airsonic/commit/325938a574538d6b9bfe1d19e4c5894e5322c4a3
This manifests an exception in the migrations on a brand new db as we try and insert a file content into the db (legacy/schema035 for the system avatar)

Fix Liquibase Postgres migrations for blob broken since 3.5.2

---

airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
airsonic-main/src/test/java/org/airsonic/player/service/SecurityServiceTestCase.java

There is a subtle bug, which manifests during media scans
/music/a2 is considered a part of /music/a
because the former only checks if it starts with the latter.
This manifests itself in the following scenario:
- 2 MusicFolders
- Music
- Music2
- During scan:
- Music goes through the MediaFile persistence, it's root folder is located (Music starts with Music) and set to Music
- Music2 goes through the MediaFile persistence, it's root folder is located (Music2 starts with Music) and set to Music -> INCORRECT (should be set to Music2)
This happens because identity is not being properly checked.
With this PR:
- Music2 != Music
- Music2/ != Music
- Music2 != Music/
- Music2/ != Music/
- Music2 does not start with Music/
Thus all Music checks fail, and Music2 is not considered in Music
Music2 …

Fix checking whether file is in folder or not

---

.travis.yml
airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java
airsonic-main/src/main/java/org/airsonic/player/dao/ArtistDao.java
airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
airsonic-main/src/main/java/org/airsonic/player/dao/MusicFolderDao.java
airsonic-main/src/main/java/org/airsonic/player/dao/PodcastDao.java
airsonic-main/src/main/java/org/airsonic/player/spring/DatabaseConfiguration.java
airsonic-main/src/main/resources/liquibase/10.6/changelog.xml
airsonic-main/src/main/resources/liquibase/10.6/timestamp-precision.xml
airsonic-main/src/main/resources/liquibase/db-changelog.xml
airsonic-main/src/main/resources/liquibase/legacy/schema37.xml
airsonic-main/src/test/java/org/airsonic/player/TestCaseUtils.java
airsonic-main/src/test/java/org/airsonic/player/api/AirsonicRestApiIntTest.java
airsonic-main/src/test/java/org/airsonic/player/api/jukebox/AbstractAirsonicRestApiJukeboxIntTest.java
airsonic-main/src/test/java/org/airsonic/player/dao/DaoTestCaseBean2.java
airsonic-main/src/test/java/org/airsonic/player/dao/MusicFolderDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/LegacyDatabaseStartupTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaScannerServiceTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/AbstractAirsonicHomeTest.java
airsonic-main/src/test/java/org/airsonic/player/util/EmbeddedTestCategory.java

Run tests against external DBs to account for regressions, incompatible SQL, migrations and variations in cross-DB behavior.
External DBs added are:
- Postgres 9.6, 12.2 (latest)
- MySQL 5.7, 8.0 (latest)
- MariaDB 10.2, 10.5 (latest)
Some tests don't make sense running against external DBs (like LegacyDB tests). These have been marked to not run for external DBs via JUnit categories.
Minor bugs that surfaced were detected and fixed.

Add external db testing

---

airsonic-main/src/main/java/org/airsonic/player/service/scrobbler/LastFMScrobbler.java

This is the exact change in https://github.com/airsonic/airsonic/pull/775/files
The change was somehow reverted in https://github.com/airsonic/airsonic/commit/e3b3bc9d2bf0f71f2e0d4788a704a7326de3be9b in https://github.com/airsonic/airsonic/pull/1224
Should fix https://github.com/airsonic-advanced/airsonic-advanced/issues/110

Fix last fm issue where scrobbling does not happen

---

airsonic-main/src/main/java/org/airsonic/player/service/AudioScrobblerService.java

Dumb error, we're decoding but not using the decoded creds.
Should fix #114

Fix scrobbling password bug

---

install/docker/pom.xml
integration-test/pom.xml
pom.xml

Old spotify plugin isn't being maintained actively anymore, including no bugfixes etc.
Also throws the following exception at every build
```
[WARNING] unable to get access token for Google Container Registry, configuration for building image will not contain RegistryAuth for GCR
java.io.IOException: Error code 404 trying to get security access token from Compute Engine metadata for the default service account. This may be because the virtual machine instance does not have permission scopes specified.
at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken (ComputeEngineCredentials.java:111)
at com.google.auth.oauth2.OAuth2Credentials.refresh (OAuth2Credentials.java:149)
at com.spotify.docker.client.auth.gcr.ContainerRegistryAuthSupplier$DefaultCredentialRefresher.refresh …
```

Switch to a different maven docker plugin for building

---

airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp

Play queue display on web client is extremely slow for large play queues.
The data transfer isn't actually the bottleneck, it's actually the page rendering and the dom manipulation. For a play queue of about 800 songs, it is enough to cause the browser to bog down and lag such that it starts missing ping checks and consequently is disconnected from the server before the play queue has even rendered.
Upon profiling, the bulk of the time is actually spent in this particular section of the code, which isn't even needed considering the elements are already in a non-hidden state when cloned.
Taking out this code reduces the time spent per loop from about 1s (rendering 1 row per sec) to about 100ms. For 800 songs in a play queue, the result is rendered much much faster ~10X faster (from ~800 …

Optimize playqueue rendering

---

airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/test/java/org/airsonic/player/service/SettingsServiceTestCase.java

- changed name of property migration compatibility property (`PropertiesFileUpgradeRetainCompatibility` -> `PropertiesFileRetainObsoleteKeys`)
- check key exists before migrating, mostly to clear out redundant logs
- no exceptions made for deleting keys if retention property says so

Minor tweaks to property migration: always check if property exists + never delete if option set

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java

Media file updates were not always evicting cache entries.
This ensures they are evicted.

Fix cache eviction for media file updates

---

airsonic-main/src/main/java/org/airsonic/player/ajax/PlayQueueInfo.java
airsonic-main/src/main/java/org/airsonic/player/ajax/PlayQueueWSController.java
airsonic-main/src/main/java/org/airsonic/player/controller/ExternalPlayerController.java
airsonic-main/src/main/java/org/airsonic/player/controller/HLSController.java
airsonic-main/src/main/java/org/airsonic/player/controller/M3UController.java
airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
airsonic-main/src/main/java/org/airsonic/player/security/JWTAuthenticationProvider.java
airsonic-main/src/main/java/org/airsonic/player/security/JWTAuthenticationToken.java
airsonic-main/src/main/java/org/airsonic/player/security/JWTRequestParameterProcessingFilter.java
airsonic-main/src/main/java/org/airsonic/player/service/JWTSecurityService.java
airsonic-main/src/main/java/org/airsonic/player/service/PlayQueueService.java
airsonic-main/src/main/java/org/airsonic/player/service/ShareService.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/AlbumUpnpProcessor.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/CustomContentDirectory.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/DispatchingContentDirectory.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/FolderBasedContentDirectory.java
airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
airsonic-main/src/test/java/org/airsonic/player/service/JWTSecurityServiceTest.java

This fixes the external Playlist bug #174, and makes some changes to the JWTs to allow playing via external players:
- The expected behavior is:
- Download an m3u at player initialization if player is an external player (EXTERNAL_WITH_PLAYLIST or EXTERNAL)
- No need to press play/pause
- Download an m3u every time the playlist changes after initialization if the player is an EXTERNAL_WITH_PLAYLIST player (the m3u needs to be updated to reflect the new songs added)
- No need to download it for EXTERNAL because the original m3u should continue working (only has reference to the player and the playqueue changes are reflected on the server, not in the m3u)
- We can switch to downloading with play/pause button (as before) later if it generates a large number of m3us for EXTERNAL_WITH_PLAYLIST …

Fix External Player Bug

---

airsonic-main/src/main/webapp/WEB-INF/jsp/index.jsp

The top panel remains an iframe (hasn't been converted yet).
This poses layout problems, especially since it is the first element in the layout. Because the iframe contents haven't loaded yet, the iframe height is set by the useragent to be 150px. Since that is the initial basis for flex, it goes from there and stays at that height.
The approach here is to wait for the contents of the iframe to load and then set the iframe height forcibly afterwards via javascript. This means we can take it out of the flex equation altogether, so the bottom panel effectively flexes to take the rest of the space.

Set top panel iframe height via javascript

---

airsonic-main/src/main/java/org/airsonic/player/ajax/LyricsWSController.java
airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
airsonic-main/src/main/java/org/airsonic/player/io/PipeStreams.java
airsonic-main/src/main/java/org/airsonic/player/io/ShoutCastOutputStream.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
airsonic-main/src/main/java/org/airsonic/player/service/SonosService.java
airsonic-main/src/main/java/org/airsonic/player/service/jukebox/AudioPlayer.java
airsonic-main/src/main/java/org/airsonic/player/service/jukebox/PlayerTest.java
airsonic-main/src/main/java/org/airsonic/player/service/metadata/MetaDataParserFactory.java

Most other suggestions are useless. Either third party library audits, or incorrect assumptions (http => https for plugin repo when it doesn't exist, secure cookies when we use http, inputstreams being closed later not recognized), or deliberate use cases (interned strings as sync locks)

LGTM suggestions

---

airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp

Each owner page keeps track of whether it sent a request. On callback, the owner checks if it's waiting for a callback, and executes if it is, otherwise it ignores the request. playQueue and mediaMain are the two owners in this issue.
Fixes #203

Fix two dialog boxes appearing when appending to playlists

---

airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java

Spring changed implementations and was now throwing an exception instead of just refusing to match if DelegatingPasswordEncoder didn't find an id.
Example: t+s auth mechanism when encounters a bcrypt cred to match against, will issue a match against '{bcryptsalttoken}storedcred', which doesn't exist. Instead of throwing an exception, the implementation needs to say no-match so it can move on to the next cred.
Fixes #212

Fix bug when trying to connect with t+s and no encoder id is found

---

airsonic-main/pom.xml

Provides javax.xml packages that the jdk provides itself
Old dependency, it will also become an issue with Java 11 later.

Remove/Exclude Stax

---

airsonic-main/src/main/webapp/WEB-INF/jsp/head.jsp
airsonic-main/src/main/webapp/script/keyboard_shortcuts.js

Some keyboard methods being called had updated signatures but had not been updated in the JS file.
Fixes #219

Fix keyboard shortcut methods

---

airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/table.jsp

playqueue and index both call head.jsp which imports a js file for keyboard binding. this is problematic because then keyboard bindings are bound twice. now playqueue only calls include.jsp (to import jsp related things so it can compile)
Fixes #217

Fix doublebinding keyboard shortcuts

---

airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp

This prevents accidental moves that don't actually reorder rows.
Fixes #223

Do not bother server or redraw if nothing in rows has been reordered

---

airsonic-main/src/main/webapp/style/default-without-mediaelement.css

Makes playqueue line height the same as playlist line height.
Fixes #229

Make all table row line heights to be 100% instead of 190%

---

airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java

Postgres driver can only send a certain number of params over the wire in one go (32767).
This poses issues for `IN` statements with a large number of params (such as a large number of media files being marked present simultaneously).
Base airsonic updated files one-by-one and thus does not come across this issue.
This fix introduces batchedUpdates so updates are still sent en masse but in batched statement form in batches that are below the postgres limit (even if the db isn't postgres). Those drivers that do not support batched updates (maybe HSQLDB 1.8?) will send statements over one by one.
The overall outcome is that the statement won't yield exceptions for postgres for a large number of params, BUT it will most certainly be slower than a large IN query because the query planner …

Update in batches because Postgres wire cannot handle large number of params

---

airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java

This should remove need for two trips to the DB for autogenerated columns like serial ids:
- get max id
- increment by 1 and insert into db
This not only causes unnecessary race conditions, but also slows down the application

Atomic insertion semantics for AbstractDao

---

install/docker/Dockerfile
install/docker/entry.sh
install/docker/run.sh

Combines 2 mechanisms that exist to specify the user/group to run the container. User/Group may be specified using:
- `--user` param in the docker run invocation
- `PUID` or `PGID` environment params provided to the container
The first takes precedence over the second. If neither is specified, the container runs as root (as before).
Note that the specified user/group should have write/read privileges on the volumes that are being mounted (particularly the data volume where symlinks to the transcodes/db are made)
Examples:
- `docker run --user 787:121 -v data:/var/data airsonicadvanced:airsonic-advanced:latest`
- Runs and creates files as user 781, group 121
- `docker run --user 787 -v data:/var/data airsonicadvanced:airsonic-advanced:latest`
- Runs and creates files as user 781, group 0 …

Docker puid/pgid

---

airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java

LDAP auth provider was not getting a chance at authing a user because LDAP enabled user accounts were considered being disabled
Fixes #290

Allow LDAP auth provider a chance at the user auth

---

airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp

The height of the DataTable on the playlist view was limited to a maximum of 60hv. In the album view there is no limit. I found the same setting there, but commented out. So I removed it in both views.
Now the height of the DataTable is now longer limited and only bound to the number chosen in "Show x entries". @randomnicode I'm now defenitly getting what you ment in #274 with the custom height ;-)
With the current release I'm getting two vertical scroll bar in the playlist view (one on the datatable and one in the main iframe), with e.g. "All" selected in "Show x entries" and a long playlist. This issue is getting resolved with this pull request as well. I'm happy tough with just one vertical scroll bar now :-)
Can be reproduced on other sceen resolutions when zooming in with the browser …

Remove scollY (height limit) on playlist datatable

---

airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playlists.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannel.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannels.jsp

Reduce it to a standard "medium" (160) instead of a custom 200
Difference looks like:
vs
--
vs

Smaller size cover art for display

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java

Discovered during discussions in https://github.com/airsonic/airsonic/pull/1662

Shut down scan pool properly in case of exceptions

---

airsonic-main/src/main/java/org/airsonic/player/service/InternetRadioService.java

Fixes this issue https://github.com/airsonic/airsonic/issues/1209
In the current release the specified radio url in the settings should point to a m3u-file containing urls to radio streams.
With this update you can now also directly specify the url to a binary radio stream.

Update InternetRadioService to support direct binary urls

---

README.md
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java

Because IgnoreFileTimeStamps is useful at a technical level but does not describe the high level reason of the property

Rename IgnoreFileTimestamps to FullScan

---

airsonic-main/src/main/webapp/WEB-INF/jsp/left.jsp

This should allow seeing the radio station name if it doesn't fully fit in the view.
This is *not* tested, as I do not have an environment to test in, however it's fairly simple and should have no problems as long as quotes are being escaped somewhere (they generally aren't be in URLs anyways)
Contributing
1.  **License Acceptance** All contributions must be licensed as [GNU GPLv3](https://github.com/airsonic/airsonic/blob/develop/LICENSE.txt) to be accepted. Use [`git commit --signoff`](https://jk.gs/git-commit.html) to acknowledge this.
I'm in the browser, and I'm pretty sure this is trivial enough to not need it? I can (eventually) clone locally if necessary, but my current environment is broken due to a partially restored backup.

Put radio station names in title attribute

---

airsonic-main/src/main/java/org/airsonic/player/controller/TranscodingSettingsController.java
airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java
airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
airsonic-main/src/main/webapp/WEB-INF/jsp/transcodingSettings.jsp

Transcoding converts a source file to a transcoded file using a specified target bitrate.
When transcoding on the fly, the final size of the transcoded file is unknown until the transcoding finishes.
However, for the sake of seeking and other things, browsers and other clients require the final size of the transcoded file to be sent upfront at the beginning.
Airsonic server estimates the final size of the transcoded file and sends it to the client at the start of the transcode.
The estimated size used to be calculated as:
Transcoded Size = Target Bitrate x (Source duration + 2s) 
The extra 2s are added as a safety guard in case the estimate turns out to be an underestimate and the final size turns out to be bigger. This is likely because bitrates are average estimates. In this scenario, …

Add transcode estimate paddings as a global setting

---

install/docker/Dockerfile

If needed, can run using `docker run --init`

Remove tini from Dockerfile

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java

Originally pointed by and fixes: https://github.com/airsonic/airsonic/issues/1840
Retrieving media file data (folder artist) instead of artist id3 data

Fix getArtist endpoint starred data

---

airsonic-main/src/main/java/org/airsonic/player/spring/WebsocketConfiguration.java

Continuation of the issue in https://github.com/airsonic-advanced/airsonic-advanced/pull/433
Hopefully prevents people needing to add empty Origin headers in proxies like in https://github.com/airsonic-advanced/airsonic-advanced/issues/462

Fix CORs Origin pattern again

---

airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
airsonic-main/src/test/java/org/airsonic/player/security/RESTAuthTest.java

Adds support for using HTTP basic authentication with REST API instead of passing credentials in query string.

rest api: add support for basic auth

---

airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
airsonic-main/src/main/resources/liquibase/11.0/insert-mod-transcoding.xml
install/docker/Dockerfile

Will need to register the following extensions as Music types in Settings -> General also
alm 669 mdl far xm mod fnk imf it liq wow mtm ptm rtm stm s3m ult dmf dbm med okt emod sfx m15 mtn amf gdm stx gmc psm j2b umx amd rad hsc flx gtk mgt mtp
Default adds these already, but won't override if a custom list already exists in the parameter file, so do add them.
Note, needs xmp. In Docker container, xmp is installed.
Fixes https://github.com/airsonic/airsonic/issues/1698

Add mod transcoding to mp3 and install xmp in docker container to decode mod files

---

airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java

Order Albums by a secondary index other than create_date as create_dates are not unique

---

airsonic-main/src/main/java/org/airsonic/player/ajax/TagWSController.java
airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java
airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java
airsonic-main/src/test/java/org/airsonic/player/service/metadata/MetaDataFactoryTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/metadata/MetaDataParserTestCase.java

Previously only parsed video files.
Now logic is:
- jaudiotagger: certain extensions
- ffmpeg: all
- default file-based: all
Will eventually rework to gather info from all tag parsers and combine them

FFMPEG Metadata parse for all files

---

airsonic-main/src/main/java/org/airsonic/player/service/InternetRadioService.java

Add direct playable types of radio to audio/aac and audio/aacp in addition to audio/mpeg
Fixes part of #536

Expand direct playable types

---

airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java

Upgrading Lucene means a new index, which means a rescan needs to occur before the library stats are generated

Update dependencies (including Lucene)

---

airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java

Jaudiotagger sometimes returns strings with trailing and (rarely) embedded \0 characters, strip these before storing them in the database. This avoids problems with Postgresql (which can not store \0 in string data types) and it is more correct as these \0 characters should not be there in the first place. Strangely enough Jaudiotagger *does* strip terminating \0 characters when storing WAV info tags in ID3 fields, this patch extends this functionality to all other (string) types and also takes care of embedded stray \0's.
This patch is needed to make airsonic (any version) work reliably with Postgresql. It is a continuation of a similar PR (https://github.com/airsonic/airsonic/pull/1236) to the original airsonic which never got merged.

Strip terminating and embedded \0 in JaudioTaggerParser

---

airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
airsonic-main/src/main/webapp/script/utils.js

This pull request adds the ability to save the size of the dialog, showing when adding tracks to a playlist. I found it very annoying to change the size of this dialog every time.
The size is saved in cookies. This makes it very lightweight and also adds the possibility to have different sizes on different computers/browsers for the same user/player.
The size of the dialog, shown when adding from the album view, is stored in a different cookie then the size of the dialog shown, when adding from the player queue. Even though the initial size is 300 width and 250 height for both (height was 350 for mediaMain and 220 for playQueue).

Save "add to playlist"-dialog size

---

pom.xml

This supresses the following error which prevents building:
```
[WARNING] Unused declared dependencies found:
[WARNING]    org.springframework:spring-aspects:jar:5.3.8:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Airsonic 11.0.0-SNAPSHOT:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  0.625 s]
[INFO] Subsonic REST API .................................. SUCCESS [  2.672 s]
[INFO] Sonos API .......................................... SUCCESS [  3.297 s]
[INFO] Airsonic Main ...................................... FAILURE [ 27.158 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] …
```

fix: ignore unused declared dependency on org.springframework:spring-aspects

---

airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java

Jaudiotagger does not support APE but JaudiotaggerParser insists it does. There have been several attempts to get this fix implemented in the original Airsonic but somehow it never stuck. Jaudiotagger _DOES NOT SUPPORT APE_ (where is the BLINK tag when you need it?), using it anyway causes APE files to be registered with a duration of 0 which makes them unplayable. By removing APE from the list of supported formats the scanner uses FFmpegParser.java for the format which does work.

Jaudiotagger does not support APE

---

airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
airsonic-main/src/main/resources/liquibase/11.0/postgresql-add-rand-function.xml

Fix for #698, "Shuffle radio fails on PostgreSQL"; use a database-specific random function.
PostgreSQL uses `random()`, Mysql/MariaDB and HSQLDB use `rand()`, use `MetaData.getDatabaseProductName()` to check which DBMS is used and adjust the function name accordingly. This clause will still fail on e.g. SQL Server, Oracle and DB2 since these use totally different constructions [1] to select random rows. If these DBMS are to be supported the query needs to be restructured.
[1]
- SQL Server uses `SELECT TOP 1 column FROM table ORDER BY NEWID ();`
- Oracle uses `SELECT column FROM (SELECT column FROM table ORDER BY dbms_random.value) WHERE rownum = 1;`
- DB2 uses `SELECT column RAND () as IDX  FROM table ORDER BY  IDX FETCH FIRST 1 ROWS ONLY;`

Use database-specific random function

---

airsonic-main/src/main/java/org/airsonic/player/domain/MediaFile.java

Path names with periods (.) in them get truncated after the last occurrence of such - fix this (Fixes #767 ).

Fix problem with path names containing periods (.) being truncated after the last occurrence of such (fixes #767)

---

airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java

This change contains the following fixes:
- make podcast downloads more robust in the face of concurrent channel refresh attempts, this fixes the relevant portion of #774 (Duplicated podcasts)
- get rid of the annoying `InvalidAudioFrameException` log spam on every podcast download by delaying the creation of the episode MediaFile until the file has actually been downloaded
- reset channel status to `COMPLETED` in case of interrupted channel refresh attempts

Fix multiple podcast downloads (fixes #774)

---

.github/workflows/edge.yml
.github/workflows/pr_ci.yml
.github/workflows/stable.yml
.mvn/maven.config
CONTRIBUTING.md
README.md

Adds [maven.config file](https://maven.apache.org/configure.html#mvn-maven-config-file) which allows running `mvn` command without specify settings file every time.

add maven.config

---

airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/playlist/DefaultPlaylistImportHandler.java
airsonic-main/src/main/java/org/airsonic/player/service/playlist/PlaylistImportHandler.java
airsonic-main/src/main/java/org/airsonic/player/service/playlist/XspfPlaylistImportHandler.java

Playlist import now resolves relative paths against all the following and adds all files matching contained in them:
- playlist home
- all music folders
- directory home (.)
absolute urls are not resolved against anything.
The tradeoff is speed. Playlist import might be slightly slower now because it looks in more places.
TO DO: Look for playlist items only in the folders the user has permission for.

Playlist Import Resolution

---

airsonic-main/src/main/java/org/airsonic/player/controller/CoverArtController.java
airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/domain/CoverArt.java
airsonic-main/src/main/java/org/airsonic/player/service/CoverArtService.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java

Use null-object pattern for cover art to cache nulls from the db
Use minimizeDiskAccess to not check for parent file timestamps or recreate it from scratch.
~Need to ensure that == is the appropriate equality operator for NULL_COVERART in case it serializes and deserializes from the cache~ Using .equals now.
Alleviates or fixes #828

Speed up parent retrieval and cover art scan during scanning

---

airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java

In FFmpegParser, when parsing JSON data, because the trackNumber and year fields in MetaData are of integer type, you need to judge whether it is a number when converting string to int.
To fix issue #887

Check whether track and date are numbers

---

airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
airsonic-main/src/main/resources/liquibase/11.0/explicit-fk-indices.xml
airsonic-main/src/main/resources/liquibase/11.0/podcast-episode-indices.xml

Mostly meant for postgres since it does not automatically create indices on the referential side of the fk, though publish date and episode_guid indices were added to speed up podcasts
Fixes #902

Add indices to speed up retrievals (particularly for postgres)

---

contrib/airsonic.service

Should fix https://github.com/airsonic-advanced/airsonic-advanced/issues/846 and other crashes related to backup.
See https://github.com/airsonic-advanced/airsonic-advanced/issues/846#issuecomment-2008312228 for a detailed explanation on the reason behind this change.
I see I didn't sign this commit (edited online here on GitHub, don't know if it's possible to sign a commit from there?), but I do acknowledge the licensing requirements of contributions.

Updated SystemCallFilter in SystemD service template
