airsonic-advanced/airsonic-advanced

- airsonic-main/src/main/java/org/airsonic/player/domain/PlayQueue.java
- airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java
- airsonic-main/src/main/java/org/airsonic/player/service/search/SearchServiceUtilities.java
- airsonic-main/src/main/java/org/airsonic/player/spring/RegisterPrecompiledJSPInitializer.java
Mostly same PR (cherry-picked) as https://github.com/airsonic/airsonic/pull/1365
> Removed duplicated code and other cleanups

- airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/ArtistDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PlayQueueDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PlayerDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PlaylistDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PodcastDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/RatingDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/ShareDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/TranscodingDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
- airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
Few cosmetic changes in the process of centralizing the dao more.
- Fixed some generics warnings
- commonized some methods
- make nearly all daos use a method in the abstract dao instead of the jdbctemplate directly
> Minor changes to dao structure

- airsonic-main/pom.xml
- pom.xml
https://github.com/spring-projects/spring-boot/releases/tag/v2.2.2.RELEASE
> Bump Spring Boot to 2.2.2

- airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
- airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java
- integration-test/src/test/resources/features/api/stream-flac-as-mp3.feature
- integration-test/src/test/resources/features/api/stream-m4a-as-mp3.feature
Same PR as https://github.com/airsonic/airsonic/pull/1123
> Seekable transcodes

- airsonic-main/src/main/java/org/airsonic/player/controller/CoverArtController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
- airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java
based on https://github.com/airsonic/airsonic/pull/1467 and https://github.com/airsonic/airsonic/pull/1466
> Clean jaudio taggers + fix potential nullptr dereferencing

- airsonic-main/src/main/java/org/airsonic/player/io/PlayQueueInputStream.java
> Fix minor bug while streaming

- airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
- airsonic-main/src/main/java/org/airsonic/player/spring/CacheConfiguration.java
Cache user settings so we don't ask the db multiple times
> Add user settings cache

- airsonic-main/src/main/webapp/WEB-INF/jsp/artistMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/changeCoverArt.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/jquery.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/starred.jsp
Based on https://github.com/airsonic/airsonic/pull/1455
> Remove main menu boldness

- airsonic-main/src/main/resources/org/airsonic/player/theme/default_dark.properties
- airsonic-main/src/main/resources/org/airsonic/player/theme/default_light.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/icons/default_dark/chevrons-down.svg
- airsonic-main/src/main/webapp/icons/default_dark/chevrons-up.svg
- airsonic-main/src/main/webapp/icons/default_light/chevrons-down.svg
- airsonic-main/src/main/webapp/icons/default_light/chevrons-up.svg
Same as https://github.com/airsonic/airsonic/pull/1539
> Toggle play queue with a button

- airsonic-main/src/main/java/org/airsonic/player/security/CsrfSecurityRequestMatcher.java
- airsonic-main/src/main/java/org/airsonic/player/spring/WebsocketConfiguration.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/albumMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/artistMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/changeCoverArt.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/editTags.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/index.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/left.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/lyrics.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/more.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/right.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/starred.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/top.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/videoPlayer.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/websocket.jsp
Previously each jsp page opened its own connection to the server, which led to a lot of connections per page.
This consolidates all websockets into a master object that coordinates websocketing behavior on the page.
Add security also + some bugfixes.
> Consolidate websockets

- airsonic-main/src/main/resources/liquibase/10.6/user-credentials.xml
Should fix https://github.com/airsonic-advanced/airsonic-advanced/issues/101
> Fix postgres SQL migration for user db

- install/docker/Dockerfile
- integration-test/pom.xml
- integration-test/src/test/java/org/airsonic/test/StreamIT.java
> Update Docker to base openjdk11:alpine-jre

- airsonic-main/pom.xml
- airsonic-main/src/main/java/org/airsonic/player/controller/UploadController.java
- airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/upload.jsp
- pom.xml
Allows upload and extraction of:
- 7z
- rar
- zip
- tar
Also tries to extract everything instead of giving up the whole operation if an error occurs in one file
> Add support for uploading different types of archives

- airsonic-main/pom.xml
- airsonic-main/src/main/java/org/airsonic/player/service/search/AnalyzerFactory.java
- airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
- airsonic-main/src/main/java/org/airsonic/player/service/search/IndexType.java
- airsonic-main/src/main/java/org/airsonic/player/service/search/QueryFactory.java
- airsonic-main/src/main/resources/org/airsonic/player/service/search/analysis/stopwords.txt
- airsonic-main/src/main/resources/org/airsonic/player/service/search/analysis/stopwords_artist.txt
- airsonic-main/src/test/java/org/airsonic/player/service/search/AnalyzerFactoryTestCase.java
- airsonic-main/src/test/java/org/airsonic/player/service/search/QueryFactoryTestCase.java
- airsonic-main/src/test/java/org/airsonic/player/service/search/SearchServiceStartWithStopwardsTestCase.java
Combination of
- https://github.com/airsonic/airsonic/pull/1235
- https://github.com/airsonic/airsonic/pull/1526
and Lucene upgrade
Index version updated to 18 to keep consistency with Airsonic for now.
> Improve Lucene Search and upgrade Lucene (8.2.0 -> 8.4.1)

- pom.xml
> Fix fourthline repo

- .github/workflows/pr_ci.yml
- .travis.yml
- airsonic-main/src/main/java/org/airsonic/player/spring/DatabaseConfiguration.java
- airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
Switch building PRs from Travis to GitHub Actions
> GitHub Actions: Build PRs

- .github/workflows/edge.yml
> Only build merged pull requests

- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
- Nulls appearing in tables
- UTF-8 encoding
- Checkboxes on drop down select all or select none
- onStop() being sent with uninitialized player id at startup
> Various fixes for playlist and playqueue

- airsonic-main/src/main/webapp/WEB-INF/jsp/changeCoverArt.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/jquery.jsp
> Remove cloneNodeBySelector from general shared script and put it only in page that uses it

- .github/workflows/pr_ci.yml
- airsonic-main/pom.xml
- integration-test/pom.xml
- pom.xml
plugin dependency management is also now done by Spring leading to removal of a lot of custom dependency management
> Spring Boot 2.2.6

- airsonic-main/src/main/webapp/WEB-INF/jsp/index.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
> Style fixes

- airsonic-main/pom.xml
It is provided by spring-boot-starter-parent already
> Remove extra war repackage execution

- airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannel.jsp
JS was sending problematic url string to server
Fixes #197
> Fix podcast page js

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
> Fix redrawing entire table when starring

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
> Add pointer for media main buttons

- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
- airsonic-main/src/main/webapp/style/default-without-mediaelement.css
seq is the first column for all tables now.
> Fix seqs in playlist to make the table column layouts consistent

- airsonic-main/src/main/resources/liquibase/10.6/add-media-file-mb-recording-id.xml
- airsonic-main/src/main/resources/liquibase/10.6/support-listenbrainz.xml
- airsonic-main/src/main/resources/liquibase/10.6/user-credentials.xml
- airsonic-main/src/main/resources/liquibase/6.3/add-player-mixer.xml
- airsonic-main/src/main/resources/liquibase/6.4/add-album-mb-release-id.xml
- airsonic-main/src/main/resources/liquibase/6.4/add-media-file-mb-release-id.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema25.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema26.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema28.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema29.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema30.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema32.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema35.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema36.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema38.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema43.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema45.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema46.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema47.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema49.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema52.xml
- airsonic-main/src/main/resources/liquibase/legacy/schema53.xml
> Expand checksums for varchar migrations because they may be any custom number

- .github/workflows/edge.yml
- pom.xml
> Dependency check revert

- airsonic-main/src/main/webapp/WEB-INF/jsp/top.jsp
> Remove hidden clickable anchor tag around user icon

- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
Now Playing button now animates scrolling to and blinking the playing song.
Addresses #218
> Scroll to Now Playing

- airsonic-main/src/main/java/org/airsonic/player/controller/CredentialsManagementController.java
- airsonic-main/src/main/java/org/airsonic/player/validator/CredentialsManagementValidators.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/credentialsSettings.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/helpToolTip.jsp
- Fix validation
- Fix adminControl redirecting to weird zone
- admincontrol form now has abs url instead of relative
- utf8 pages
Validation issue discovered in https://github.com/airsonic-advanced/airsonic-advanced/issues/212#issuecomment-618107741
> Cred settings fixes

- airsonic-main/pom.xml
- airsonic-sonos-api/pom.xml
- install/docker/pom.xml
- integration-test/pom.xml
- pom.xml
- subsonic-rest-api/pom.xml
Same functionally as the stable release or the previous edge release
> Increment snapshot version to 11.0.0-SNAPSHOT

- airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
> Media file missing optimizations and bugfixes

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
> Fix Podcast durations

- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
Mostly same as https://github.com/airsonic/airsonic/pull/1659 but with some tweaks
> Media Session API

- airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
Need to change them to Strings
> Fix paths in insert statements

- airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/ShareDao.java
MySql does not return with column name rather a GENERATED_KEY name
> Fix issues with Mysql autogenerate key

- airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java
> Ability to provide alternative column names in Beans

- airsonic-main/src/main/java/org/airsonic/player/dao/TranscodingDao.java
Using the new abstractdao semantics
> TranscodingDAO atomic inserts

- .github/workflows/pr_ci.yml
- install/docker/Dockerfile
- install/docker/run.sh
We were using alpine which might be causing some issues in some dependency somewhere because it uses musl instead of glibc
Possible fix for #198 and #267
> Update docker base to 14-jre and Ubuntu-base

- install/docker/Dockerfile
- install/docker/run.sh
to help folks overriding entrypoints like in #267
> add tini to PATH in docker container

- install/docker/entry.sh
Logic change to cater to additional requirement to reuse the same container in #157
> Change logic to account for restarting existing containers

- airsonic-main/src/main/java/org/airsonic/player/dao/TranscodingDao.java
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/drop-rename-transcoding.xml
- airsonic-main/src/test/java/org/airsonic/player/dao/TranscodingDaoTestCase.java
Drop transcoding and player_transcoding
Rename transcoding2 and player_transcoding2 to the former respectively
> Clean up transcoding tables

- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
> Fix rollbackfile env param

- airsonic-main/src/main/java/org/airsonic/player/controller/ExternalPlayerController.java
- airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
- airsonic-main/src/main/java/org/airsonic/player/security/JWTAuthenticationProvider.java
- airsonic-main/src/main/java/org/airsonic/player/security/JWTAuthenticationToken.java
- airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
The core issue is a circular dependency outlined here: https://github.com/spring-projects/spring-data-examples/issues/189
JWT issue seems to also be a bug
Fixes #286
> Fix ldap auth issue + fix jwt issue

- airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
Similar to and supersedes #285
Thanks to @Faeb35
> Fix album download NPE

- airsonic-main/src/main/java/org/airsonic/player/command/PersonalSettingsCommand.java
- airsonic-main/src/main/java/org/airsonic/player/controller/PersonalSettingsController.java
- airsonic-main/src/main/java/org/airsonic/player/domain/UserSettings.java
- airsonic-main/src/main/java/org/airsonic/player/service/AudioScrobblerService.java
- airsonic-main/src/main/java/org/airsonic/player/service/scrobbler/ListenBrainzScrobbler.java
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/personalSettings.jsp
Requested here: https://github.com/airsonic/airsonic/issues/1703
> Allow custom URL for listenbrainz

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_bg.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ca.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_cs.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_el.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en_GB.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_et.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fi.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_is.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_it.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ja_JP.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ko.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_mk.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nn.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_no.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pl.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_pt_PT.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_ru.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sl.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_sv.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_uk.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_zh_CN.properties
> Fix getting started page truncated

- airsonic-main/src/main/java/org/airsonic/player/service/InternetRadioService.java
Successor to #309
Pushed due to inactivity in the predecessor.
Just adds a commit that fixes a minor leak
> Internet Radio to support direct radio streams

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/credentialsSettings.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/userSettings.jsp
Also add info about how to CHANGE password.
Per suggestion in and closes https://github.com/airsonic-advanced/airsonic-advanced/issues/325
> Add warning and make more explicit that creds are immutable

- install/docker/run.sh
- Don't create symlinks if files already present (for instance, mounted externally)
- Fix outdated spring-boot property
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/340
> Docker symlinks to external libraries

- README.md
- airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
Because we have use cases that require one deep scan but not recurring one
Discussed here: https://github.com/airsonic-advanced/airsonic-advanced/pull/317#issuecomment-636020295
> Add ClearFullScanSettingAfterScan property

- airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
Identified by and potential fix for https://github.com/airsonic-advanced/airsonic-advanced/issues/349
Also resolve potential deadlock issues by updating/inserting only distinct albums
> Fix album duration + count update bug. Also possibly fix potential deadlock

- airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
Fix regression introduced in https://github.com/airsonic-advanced/airsonic-advanced/commit/d58ae2645796e97b933614978740a8fd1fb85b9b#diff-5985fe79fe475a0a0fa60d8dda2d3dc9
that accidentally took away the refresh button feature
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/366
> Fix Refresh button link

- airsonic-main/src/main/java/org/airsonic/player/spring/WebsocketConfiguration.java
Due to https://github.com/spring-projects/spring-framework/issues/26111
> Fix websockets issue with update to Spring boot 2.4.2

- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
Feature request in https://github.com/airsonic-advanced/airsonic-advanced/issues/422
Flexes media player (initial width of 300px)
> Flex timeline for audioplayer

- airsonic-main/src/main/java/org/airsonic/player/controller/PodcastChannelsController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/PodcastController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
- airsonic-main/src/main/java/org/airsonic/player/domain/PodcastExportOPML.java
- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannels.jsp
Mentioned here: https://github.com/airsonic/airsonic/issues/1422
> Provide ability to export podcasts to OPML format

- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/podcast-description-text.xml
> Convert podcast description to text to accomodate larger text data

- airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java
- airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
- airsonic-main/src/main/java/org/airsonic/player/service/playlist/DefaultPlaylistImportHandler.java
- airsonic-main/src/main/java/org/airsonic/player/service/playlist/XspfPlaylistImportHandler.java
- airsonic-main/src/test/java/org/airsonic/player/service/SecurityServiceTestCase.java
Issue mentioned here: https://github.com/airsonic/airsonic/issues/1731
Will resolve paths relative to the playlist folder (even when importing adhoc)
> Relative paths in playlists

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/326
Thanks @The-Exterminator
(A bit outdated again!)
Sorry for taking so long!
> Update Danish translation

- airsonic-main/src/main/java/org/airsonic/player/controller/SearchController.java
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/447
> Use id3 index for searches also

- airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp
- install/docker/run.sh
Add semicolon at end of JS
Echo context path in docker container
> Minor things

- airsonic-main/pom.xml
Enhancement per https://github.com/spring-projects/spring-boot/issues/24744
Faster performance for EL expressions
> Remove Glassfish Jakarta EL and switch to Tomcat's EL

- .github/workflows/edge.yml
> Test multiplatform release

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
Perhaps fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/470
> Sanitize and decode URLs properly for podcasts

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
Some podcasts feed urls apparently require a user-agent or they send back 404s.
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/471
> Add User-Agent to outgoing podcast requests

- airsonic-main/src/main/webapp/WEB-INF/jsp/videoPlayer.jsp
- airsonic-main/src/main/webapp/icons/video/maximize.svg
- airsonic-main/src/main/webapp/script/videoPlayerCast.js
- airsonic-main/src/main/webapp/style/videoPlayer.css
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/446
> Video full screen

- airsonic-main/src/main/java/org/airsonic/player/controller/CoverArtJspController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/RatingJspController.java
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/478
> Pass params to JSP pages when redirecting from REST calls

- airsonic-main/src/main/webapp/WEB-INF/jsp/gettingStarted.jsp
Fixes https://github.com/airsonic/airsonic/issues/1837 and https://github.com/airsonic/airsonic/issues/1769
> Escape JSP string quotes in JS

- airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/ArtistDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PodcastDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/RatingDao.java
Ensuring pageable api calls provide responses with consistent ordering
> Adding unique secondary index to order bys

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_da.properties
Thanks to @The-Exterminator
Fixes #486
> Updated Danish language

- airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java
> Extract tags from secondary tag places like in streams in opus files

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
despite async callbacks
Problem shared here: https://www.reddit.com/r/airsonic/comments/lyu0xn/header_following_in_airsonic_advanced_vs/gpy95sh?utm_source=share&utm_medium=web2x&context=3
> Insert thumbs in GridView in the same order as in ListView

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
Issues with urls like 
"https://anchor.fm/s/1f6ce87c/podcast/play/27662190/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2021-03-02%2F839452e34dd1462870562602afe44cbb.m4a"
that are deliberately encoding http parameters as redirection paths to the server
Fixes #502
> Force URL decode for Padcast filenames, but otherwise keep intact unless there's no url detected

- airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java
Change cover display for album so we do not display always first image from file tag but image that is marked as front cover.
Proposed fix for #511.
> Change cover display for album

- SONOS.md
Changed the heading for "the One User" topic to add anonymous.  For clarity.
Guidelines for Contributing
---------------------------
Airsonic development is a community project, and contributions are welcomed. Here are a few guidelines you should follow before submitting:
1.  **License Acceptance** All contributions must be licensed as [GNU GPLv3](https://github.com/airsonic/airsonic/blob/develop/LICENSE.txt) to be accepted. Use [`git commit --signoff`](https://jk.gs/git-commit.html) to acknowledge this.
2.  **No Breakage** New features or changes to existing ones must not degrade the user experience. This means do not introduce bugs, remove functionality, or make large changes to existing themes/UI without prior discussion in an Issue.
3.  **Coding standards** Language best-practices …
> Minor doc edits

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
Previously not escaping for folder views
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/545
> Escape HTML chars in albums/artists

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
Resulted in bad release.
Fixes #553
> Fix html escape errors

- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
> Fix Top Songs button disappearing

- SONOS.md
Added more explicit language to the root host URL to the Endpoint URL docs - and Root URL.
Guidelines for Contributing
---------------------------
Airsonic development is a community project, and contributions are welcomed. Here are a few guidelines you should follow before submitting:
1.  **License Acceptance** All contributions must be licensed as [GNU GPLv3](https://github.com/airsonic/airsonic/blob/develop/LICENSE.txt) to be accepted. Use [`git commit --signoff`](https://jk.gs/git-commit.html) to acknowledge this.
2.  **No Breakage** New features or changes to existing ones must not degrade the user experience. This means do not introduce bugs, remove functionality, or make large changes to existing themes/UI without prior discussion in an Issue.
3.  **Coding standards** Language …
> Sonos Config clarification

- airsonic-main/src/main/webapp/script/utils.js
Also consolidate the storage element
> Add checks if localstorage is present

- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
there was a trivial typo in playQueue.jsp which broke "save play queue"
this pr fixes the issue
> fix save play queue functionality

- airsonic-main/src/main/java/org/airsonic/player/util/LegacyHsqlMigrationUtil.java
> fix 2nd startup under tomcat

- airsonic-main/src/main/java/org/airsonic/player/service/scrobbler/ListenBrainzScrobbler.java
Fixes #611 
Probably assess and log error messages from listenbrainz
> Listenbrainz error msg in scrobbling

- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
Causing issues in migration
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/634
> Remove padding from string comps in hsqldb

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannel.jsp
- airsonic-main/src/main/webapp/style/default-without-mediaelement.css
> Add select all button to podcast episodes

- airsonic-main/pom.xml
- airsonic-main/src/main/resources/application.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/status.jsp
Adds cache, health and sessions in status
> Additional stats in status

- airsonic-main/src/main/java/org/airsonic/player/service/NetworkService.java
Support for looking at X-Forwarded-For and X-Forwarded-Schema
> More network headers

- airsonic-main/src/main/java/org/airsonic/player/service/NetworkService.java
Resolving follow up comment in https://github.com/airsonic-advanced/airsonic-advanced/pull/663#issuecomment-965717282
> Fix header name

- airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
Issues with filename for new playlists (that have a : due to the timestamp)
> Make sure download filename is filesystem safe

- airsonic-main/src/main/java/org/airsonic/player/util/FileUtil.java
> Log exception at lower level if trying to delete nonexistent file

- airsonic-main/src/main/java/org/airsonic/player/command/PodcastSettingsCommand.java
- airsonic-main/src/main/java/org/airsonic/player/controller/PodcastSettingsController.java
- airsonic-main/src/main/java/org/airsonic/player/dao/PodcastDao.java
- airsonic-main/src/main/java/org/airsonic/player/domain/PodcastChannelRule.java
- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/podcast-channel-rules.xml
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/podcastSettings.jsp
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/488
Does not address issue raised in https://github.com/airsonic-advanced/airsonic-advanced/issues/488#issuecomment-782873597 which may be addressed after #659
> Podcast channel rules on a per-podcast basis

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
> ZoneDatetime for some podcast dates

- airsonic-main/pom.xml
- airsonic-main/src/main/java/org/airsonic/player/service/DatabaseService.java
Bug appears for windows paths and is described here:
https://github.com/liquibase/liquibase/issues/1598
> Update liquibase for fixing extra backslashes when importing exported db

- airsonic-main/src/main/webapp/WEB-INF/jsp/status.jsp
That prevent a chart or data from presenting
> Try fixing some status jsp issues

- airsonic-main/src/main/java/org/airsonic/player/dao/MusicFolderDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/DatabaseService.java
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/move-user-table.xml
- airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
So it doesnt conflict with the postgres user keyword
Should fix https://github.com/airsonic-advanced/airsonic-advanced/issues/686
> Move user table

- airsonic-main/src/main/java/org/airsonic/player/service/DatabaseService.java
> Import db files lexicographically

- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_fr.properties
Correct spelling mistakes in the french translation.
> Correct spelling mistakes in the french translation

- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
- airsonic-main/src/main/resources/liquibase/11.0/add-wavpack.xml
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
Add "wv" (Wavpack) to the list of "Music files", To actually get Airsonic to play these files to the web player the "wv" format will need to be added the "mp3 audio" transcoder.
> Add Wavpack (wv) to the list of "Music files".

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
> Pocast NPE in if image url not present

- airsonic-main/src/main/webapp/WEB-INF/jsp/externalPlayer.jsp
> Fix external player height

- airsonic-main/src/main/resources/application.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/status.jsp
> Suppress ldap exceptions being thrown on status check

- airsonic-main/src/main/java/org/airsonic/player/security/CsrfSecurityRequestMatcher.java
- airsonic-main/src/main/resources/application.properties
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/status.jsp
> Add cache eviction control

- airsonic-main/src/main/java/org/airsonic/player/dao/PodcastDao.java
- airsonic-main/src/main/java/org/airsonic/player/domain/PodcastEpisode.java
- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/podcast-episode-guid.xml
- airsonic-main/src/test/java/org/airsonic/player/dao/PodcastDaoTestCase.java
> Ensure podcast with the same Guid or title and date or url doesn't get downloaded again

- airsonic-main/src/main/java/org/airsonic/player/util/Util.java
> Fix DLNA browsing issue

- airsonic-main/src/main/java/org/airsonic/player/service/upnp/AlbumUpnpProcessor.java
- airsonic-main/src/main/java/org/airsonic/player/service/upnp/GenreUpnpProcessor.java
- airsonic-main/src/main/java/org/airsonic/player/service/upnp/RecentAlbumUpnpProcessor.java
- airsonic-main/src/main/java/org/airsonic/player/service/upnp/UpnpContentProcessor.java
Further fixes for #740 and continuation of #741 particularly for comment  https://github.com/airsonic-advanced/airsonic-advanced/pull/741#issuecomment-1015482222
> Fix DLNA overflows in long > int casts

- airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
> Retrieve album explicitly by name

- airsonic-main/src/main/java/org/airsonic/player/spring/migrations/AddMediaFileIdToPodcastChannels.java
> Relative Path fix

- airsonic-main/src/main/resources/liquibase/11.0/relative-media-file-paths.xml
> Account for nonexisting paths in share_file and user_rating

- airsonic-main/src/main/resources/liquibase/11.0/relative-media-file-paths.xml
Fixes issue in https://github.com/airsonic-advanced/airsonic-advanced/issues/769#issuecomment-1025251914 and https://github.com/airsonic-advanced/airsonic-advanced/issues/763#issuecomment-1025198950
> Accept any checksum for relative path changeset

- airsonic-main/src/main/java/org/airsonic/player/spring/migrations/UniqueMediaFolders.java
> Guard against deleting podcast folder during migration

- airsonic-main/src/main/java/org/airsonic/player/spring/migrations/DropConstraintWithoutName.java
- airsonic-main/src/main/resources/liquibase/11.0/relative-media-file-paths.xml
> Address constraints without names

- airsonic-main/src/main/resources/liquibase/11.0/relative-media-file-paths.xml
> Delete albums with non existent folder ids prior to relativizing

- airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java
> Encountered path relative bug

- airsonic-main/src/main/java/org/airsonic/player/ajax/MediaFileWSController.java
- airsonic-main/src/main/java/org/airsonic/player/command/SearchCommand.java
- airsonic-main/src/main/java/org/airsonic/player/controller/MainController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/SearchController.java
- airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/search.jsp
Fixes #775 
Attempt at temporarily fixing while a more comprehensive system is being put in place in #786
> Fix search after relative paths

- airsonic-main/src/main/java/org/airsonic/player/command/PersonalSettingsCommand.java
- airsonic-main/src/main/java/org/airsonic/player/controller/PersonalSettingsController.java
- airsonic-main/src/main/java/org/airsonic/player/controller/SearchController.java
- airsonic-main/src/main/java/org/airsonic/player/domain/UserSettings.java
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/personalSettings.jsp
Fixes #748
Setting is on a per-user basis
> Configurable search count

- airsonic-main/src/main/java/org/airsonic/player/command/MusicFolderSettingsCommand.java
- airsonic-main/src/main/java/org/airsonic/player/controller/MusicFolderSettingsController.java
- airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
- airsonic-main/src/main/java/org/airsonic/player/dao/MusicFolderDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/MediaFolderService.java
- airsonic-main/src/main/resources/liquibase/11.0/changelog.xml
- airsonic-main/src/main/resources/liquibase/11.0/media-file-music-folder-link.xml
- airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
- airsonic-main/src/main/webapp/WEB-INF/jsp/musicFolderSettings.jsp
add fk with update and delete cascade on media folder users and media files
if folder has ancestors present, reassign
concept of deleted folders
dont delete last podcast
always keep one podcast enabled
> Media file.folder id fk

- airsonic-main/pom.xml
> Bouncy Castle for Argon Password encoder

- airsonic-main/src/main/webapp/WEB-INF/jsp/index.jsp
> Let upper scroll

- airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
- airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java
Store settings in a ConcurrentHashMap for instant retrieval instead of going digging
Remove Util.debugObject at every MediaFile update
Put a BufferedInputStream around ffprobe call in FFMpegParser
These hotspots found using a profiler
> Performance improvements

- airsonic-main/src/main/java/org/airsonic/player/service/upnp/CustomContentDirectory.java
- airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java
My try at fixing issue https://github.com/airsonic-advanced/airsonic-advanced/issues/825.
> Fix out of spec upnp duration string

- airsonic-main/src/main/java/org/airsonic/player/controller/CaptionsController.java
- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
- airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java
- airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java
> Resolve executables properly

- airsonic-main/src/main/java/org/airsonic/player/service/upnp/CustomContentDirectory.java
- airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java
> consolidate Upnp duration string

- airsonic-main/src/main/java/org/airsonic/player/dao/CoverArtDao.java
> SQL fix for MySQL coverart expunge

- airsonic-main/src/main/java/org/airsonic/player/domain/UserSettings.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/personalSettings.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
- airsonic-main/src/main/webapp/WEB-INF/jsp/playlist.jsp
By request due to discussion in #840
> Add option for AlbumArtistVisibility

- airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
- airsonic-main/src/main/java/org/airsonic/player/service/UPnPService.java
Fixes https://github.com/airsonic-advanced/airsonic-advanced/issues/861
> Consistent UPnP ID

- airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java
- airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
> Fix playqueue download

- pom.xml
https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
Guidelines for Contributing
---------------------------
Airsonic development is a community project, and contributions are welcomed. Here are a few guidelines you should follow before submitting:
1.  **License Acceptance** All contributions must be licensed as [GNU GPLv3](https://github.com/airsonic/airsonic/blob/develop/LICENSE.txt) to be accepted. Use [`git commit --signoff`](https://jk.gs/git-commit.html) to acknowledge this.
2.  **No Breakage** New features or changes to existing ones must not degrade the user experience. This means do not introduce bugs, remove functionality, or make large changes to existing themes/UI without prior discussion in an Issue.
3.  **Coding standards** Language best-practices should …
> Patch CVE-2022-22965 - Fix #878

- airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
Make seconds optional for some podcast pubdates
Fixes #881
> Fix podcast pubdate

- .github/dependabot.yml
- .github/workflows/edge.yml
- .github/workflows/pr_ci.yml
- .github/workflows/stable.yml
@randomnicode 
These changes are CI actions update patches.
This also includes the following changes.
- dependabot action for updating CI action daily.
- bug fix: stable release action failed to build
> CI action maintenance 

- airsonic-main/src/main/webapp/WEB-INF/jsp/top.jsp
> patch: add css rule to force icon size to 24px (like default icons)

- .github/workflows/codeql.yml
- .github/workflows/edge.yml
- .github/workflows/pr_ci.yml
- .github/workflows/stable.yml
- .mvn/maven.config
- install/docker/Dockerfile
@randomnicode 
I'm sorry for breaking CI by missing paramter.
I made patch to fix it.
Please review.
I removed jdk14 because temurin does not support Java 14.
To complete test, I also updated base docker image to temurin 17 jammy.
> Fix setup-java error at CI
